### ISSUE TITLE
Phase 2- Modify the tracker to include logic of promotion and demotion of the FTP server 

### ISSUE THREAD

**Issue by annieliu10** [kaiyyang/cpsc416_GroupProject_ReliableBT#2]

**Comment by Maxwell-Yang-2001** [comment]
Update: We have long since moved away from FTP server - calling it a baseline provider, if a tracker knows multiple baseline providers, it will promote a random one of them as an announce response to a peer that is not a bad actor. A baseline provider will only be "demoted" if it does not announce to the tracker in a time limit, which tracker considers as it leaving the swarm. Closing the issue.
